#define OR                              1
#define AND                             2
#define IN                              3
#define LT                              4
#define GT                              5
#define LE                              6
#define GE                              7
#define EQ                              8
#define NE                              9
#define ADD                            10
#define SUB                            11
#define MUL                            12
#define DIV                            13
#define MOD                            14
#define NOT                            15
#define SEMI                           16
#define ID                             17
#define PIPE                           18
#define JOIN                           19
#define WHERE                          20
#define INTO                           21
#define AS                             22
#define PRESERVE                       23
#define COMMA                          24
#define SSTREAM                        25
#define DQ_STRING                      26
#define SHUFFLE                        27
#define ALL                            28
#define OSTREAM                        29
#define FILTER                         30
#define TRANSFORM                      31
#define WINDOW_KW                      32
#define LP                             33
#define INT                            34
#define ROWS                           35
#define RP                             36
#define SLIDE                          37
#define SECONDS                        38
#define MINUTES                        39
#define HOURS                          40
#define DAYS                           41
#define GROUP                          42
#define BY                             43
#define REDUCE                         44
#define SQ_STRING                      45
#define DOUBLE                         46
#define TRUE                           47
#define FALSE                          48
#define NUL                            49
#define LCB                            50
#define RCB                            51
#define DOT_STAR                       52
#define COLON                          53
#define LSB                            54
#define RSB                            55
#define DOLLAR                         56
#define DOT                            57
