#define OR                              1
#define AND                             2
#define IN                              3
#define LT                              4
#define GT                              5
#define LE                              6
#define GE                              7
#define EQ                              8
#define NE                              9
#define ADD                            10
#define SUB                            11
#define MUL                            12
#define DIV                            13
#define MOD                            14
#define NOT                            15
#define SEMI                           16
#define ID                             17
#define PIPE                           18
#define SSTREAM                        19
#define DQ_STRING                      20
#define COMMA                          21
#define SHUFFLE                        22
#define ALL                            23
#define OSTREAM                        24
#define FILTER                         25
#define TRANSFORM                      26
#define WINDOW_KW                      27
#define LP                             28
#define INT                            29
#define ROWS                           30
#define RP                             31
#define SLIDE                          32
#define SECONDS                        33
#define MINUTES                        34
#define HOURS                          35
#define DAYS                           36
#define GROUP                          37
#define INTO                           38
#define BY                             39
#define REDUCE                         40
#define AS                             41
#define SQ_STRING                      42
#define DOUBLE                         43
#define TRUE                           44
#define FALSE                          45
#define NUL                            46
#define LCB                            47
#define RCB                            48
#define DOT_STAR                       49
#define COLON                          50
#define LSB                            51
#define RSB                            52
#define DOLLAR                         53
#define DOT                            54
