#define OR                              1
#define AND                             2
#define IN                              3
#define LT                              4
#define GT                              5
#define LE                              6
#define GE                              7
#define EQ                              8
#define NE                              9
#define ADD                            10
#define SUB                            11
#define MUL                            12
#define DIV                            13
#define MOD                            14
#define NOT                            15
#define SEMI                           16
#define ID                             17
#define PIPE                           18
#define SSTREAM                        19
#define DQ_STRING                      20
#define COMMA                          21
#define SHUFFLE                        22
#define ALL                            23
#define OSTREAM                        24
#define FILTER                         25
#define TRANSFORM                      26
#define WINDOW_KW                      27
#define LP                             28
#define ROWS                           29
#define INT                            30
#define RP                             31
#define SLIDE                          32
#define GROUP                          33
#define INTO                           34
#define BY                             35
#define REDUCE                         36
#define AS                             37
#define SQ_STRING                      38
#define DOUBLE                         39
#define TRUE                           40
#define FALSE                          41
#define NUL                            42
#define LCB                            43
#define RCB                            44
#define DOT_STAR                       45
#define COLON                          46
#define LSB                            47
#define RSB                            48
#define DOLLAR                         49
#define DOT                            50
